### ISSUE TITLE
KITTI GPS Fusion (Stereo + GPS) results in skew paths and one is faster than the other

### ISSUE THREAD

**Issue by mmp52** [pjrambo/VINS-Fusion-gpu#5]
When I try to run the kitti gps fusion test datase t(which I have downloaded from your link) in my jetson tx2 , system results in a funny skew paths - gps based global path and VIO path are in different orientations. Also gps path is updated slower than the other.
What can be the reason?
![screenshot_different_paths_kitti](https://user-images.githubusercontent.com/50202179/64185971-550ab400-ce6e-11e9-95e2-1aa3ed2531df.png)

And one final question, is there a script to calculate rmse between two paths , I also want to try that in euroc results for different configuration parameters.
Thanks for all of this,
Metin

**Comment by pjrambo** [comment]
1. Different orientation is normal. Since VIO is in a local frame that is relative to the frame when the initialization procedure finishes. GPS based path is in the global frame (ENU). So in most of the case, their orientations are different.

**Comment by pjrambo** [comment]
1. Different orientation is normal. Since VIO is in a local frame that is relative to the frame when the initialization procedure finishes. GPS based path is in the global frame (ENU). So in most of the case, their orientations are different.
2. GPS path is generated by a global optimization method, which may cost more computing resources. The computing resources cost is rising with time goes by. I've never tried this part in TX2 platform, maybe TX2's computing resource is not enough.
3. For calculating RMSE, you may find some code on Github. You need to align the two results and then calculate it.

**Comment by mmp52** [comment]
Thank you for your response.
How can I align them and where can I find RMSE calculating scripts on github?
Also is there a ground truth in kitti vision series, when I try to calculate RMSE what should I use as my reference ? 

Metin
